image:
  repository: acrfooddelivery.azurecr.io/order-service
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 300m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql.databases.svc:5432/order_db
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_KAFKA_BOOTSTRAP_SERVERS: food-delivery-kafka-kafka-bootstrap.kafka.svc:9092
  RESTAURANT_SERVICE_URL: http://restaurant-service.food-app.svc:8080
  USER_SERVICE_URL: http://user-service.food-app.svc:8080
  OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger-collector.observability.svc:4317
  OTEL_SERVICE_NAME: order-service

secretEnv:
  SPRING_DATASOURCE_PASSWORD:
    secretName: db-credentials
    key: POSTGRES_PASSWORD

probes:
  liveness:
    path: /actuator/health/liveness
    initialDelaySeconds: 30
    periodSeconds: 10
  readiness:
    path: /actuator/health/readiness
    initialDelaySeconds: 20
    periodSeconds: 5

ingress:
  enabled: true
  className: kong
  annotations: {}
  paths:
    - path: /api/v1/orders
      pathType: Prefix
