apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sample-jwt-secret
  namespace: food-app
spec:
  encryptedData:
    JWT_SECRET: AgBy3i4OJSWK+PiTySYZZA9rO43cGfHblbH/7iM9ZtQv+2pQ... # Dữ liệu đã mã hoá
  template:
    metadata:
      name: sample-jwt-secret
    type: Opaque
