# Kong Ingress Controller Helm values
proxy:
  type: NodePort
  http:
    nodePort: 30080
  env:
    plugins: "bundled,prometheus,opentelemetry"
  resources:
    requests:
      cpu: 300m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
