image:
  repository: ghcr.io/food-delivery-uit-project/payment-service
  tag: bbac661258bf8ef919c36c049525444f6f925a18
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 2000m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

podDisruptionBudget:
  enabled: true
  minAvailable: 1

serviceMonitor:
  enabled: true
  path: /actuator/prometheus
  interval: 15s
  scrapeTimeout: 10s

env:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql.databases.svc:5432/payment_db
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_KAFKA_BOOTSTRAP_SERVERS: food-delivery-kafka-kafka-bootstrap.kafka.svc:9092
  ORDER_SERVICE_URL: http://order-service.food-app.svc:8080
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.observability.svc:4317
  OTEL_SERVICE_NAME: payment-service
  OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=k8s-local"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus,metrics"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"

secretEnv:
  SPRING_DATASOURCE_PASSWORD:
    secretName: db-credentials
    key: POSTGRES_PASSWORD

probes:
  liveness:
    path: /actuator/health/liveness
    initialDelaySeconds: 240
    periodSeconds: 10
    timeoutSeconds: 5
  readiness:
    path: /actuator/health/readiness
    initialDelaySeconds: 240
    periodSeconds: 10
    timeoutSeconds: 5

ingress:
  enabled: true
  className: kong
  annotations:
    konghq.com/plugins: rate-limit-api, cors-plugin
  paths:
    - path: /api/v1/payments
      pathType: Prefix
